import { Button } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "./Header";
import SideBar from "./SideBar";
import Top from "./Top";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <header>Header</header>
      <SideBar />
      <Top />
      <Button colorScheme="blue">Button</Button>
    </div>
  );
}
